# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/MB_ETH_axi_smc_0.xci
# IP: The module: 'MB_ETH_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/bd_3561.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_0/bd_3561_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_1/bd_3561_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_2/bd_3561_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_3/bd_3561_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_4/bd_3561_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_5/bd_3561_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_6/bd_3561_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_7/bd_3561_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_8/bd_3561_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_9/bd_3561_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_10/bd_3561_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_11/bd_3561_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_12/bd_3561_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_13/bd_3561_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_14/bd_3561_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_15/bd_3561_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_16/bd_3561_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_17/bd_3561_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_18/bd_3561_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_19/bd_3561_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_20/bd_3561_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_21/bd_3561_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_22/bd_3561_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_23/bd_3561_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_24/bd_3561_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_25/bd_3561_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_26/bd_3561_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_27/bd_3561_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_28/bd_3561_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_29/bd_3561_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_30/bd_3561_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_1/bd_3561_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_1/bd_3561_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_2/bd_3561_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_2/bd_3561_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_3/bd_3561_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_3/bd_3561_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_4/bd_3561_arsw_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_5/bd_3561_rsw_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_6/bd_3561_awsw_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_7/bd_3561_wsw_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_8/bd_3561_bsw_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_12/bd_3561_s00a2s_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_13/bd_3561_sarn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_14/bd_3561_srn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_15/bd_3561_sawn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_16/bd_3561_swn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_17/bd_3561_sbn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_21/bd_3561_s01a2s_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_22/bd_3561_sarn_1_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_23/bd_3561_srn_1_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_24/bd_3561_m00s2a_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_25/bd_3561_m00arn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_26/bd_3561_m00rn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_27/bd_3561_m00awn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_28/bd_3561_m00wn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_29/bd_3561_m00bn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_ETH_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/MB_ETH_axi_smc_0.xci
# IP: The module: 'MB_ETH_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/bd_3561.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_0/bd_3561_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_1/bd_3561_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_2/bd_3561_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_3/bd_3561_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_4/bd_3561_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_5/bd_3561_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_6/bd_3561_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_7/bd_3561_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_8/bd_3561_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_9/bd_3561_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_10/bd_3561_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_11/bd_3561_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_12/bd_3561_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_13/bd_3561_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_14/bd_3561_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_15/bd_3561_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_16/bd_3561_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_17/bd_3561_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_18/bd_3561_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_19/bd_3561_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_20/bd_3561_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_21/bd_3561_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_22/bd_3561_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_23/bd_3561_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_24/bd_3561_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_25/bd_3561_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_26/bd_3561_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_27/bd_3561_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_28/bd_3561_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_29/bd_3561_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_30/bd_3561_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_1/bd_3561_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_1/bd_3561_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_2/bd_3561_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_2/bd_3561_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_3/bd_3561_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_3/bd_3561_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_4/bd_3561_arsw_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_5/bd_3561_rsw_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_6/bd_3561_awsw_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_7/bd_3561_wsw_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_8/bd_3561_bsw_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_12/bd_3561_s00a2s_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_13/bd_3561_sarn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_14/bd_3561_srn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_15/bd_3561_sawn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_16/bd_3561_swn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_17/bd_3561_sbn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_21/bd_3561_s01a2s_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_22/bd_3561_sarn_1_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_23/bd_3561_srn_1_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_24/bd_3561_m00s2a_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_25/bd_3561_m00arn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_26/bd_3561_m00rn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_27/bd_3561_m00awn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_28/bd_3561_m00wn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/bd_0/ip/ip_29/bd_3561_m00bn_0_ooc.xdc

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_ETH_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
