# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_uartlite_0_0/MB_ETH_axi_uartlite_0_0.xci
# IP: The module: 'MB_ETH_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_uartlite_0_0/MB_ETH_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_ETH_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_uartlite_0_0/MB_ETH_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_ETH_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_uartlite_0_0/MB_ETH_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_ETH_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_uartlite_0_0/MB_ETH_axi_uartlite_0_0.xci
# IP: The module: 'MB_ETH_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_uartlite_0_0/MB_ETH_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_ETH_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_uartlite_0_0/MB_ETH_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_ETH_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/vlsiuser/MB_ETH/NEX_ETH_IP/NEX_ETH_IP.srcs/sources_1/bd/MB_ETH/ip/MB_ETH_axi_uartlite_0_0/MB_ETH_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_ETH_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
