# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/MB_ETH/MB_ETH.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH || ORIG_REF_NAME==MB_ETH} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_microblaze_0_0/MB_ETH_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_microblaze_0_0 || ORIG_REF_NAME==MB_ETH_microblaze_0_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_dlmb_v10_0/MB_ETH_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_dlmb_v10_0 || ORIG_REF_NAME==MB_ETH_dlmb_v10_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_ilmb_v10_0/MB_ETH_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_ilmb_v10_0 || ORIG_REF_NAME==MB_ETH_ilmb_v10_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_dlmb_bram_if_cntlr_0/MB_ETH_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_ETH_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_ilmb_bram_if_cntlr_0/MB_ETH_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_ETH_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_lmb_bram_0/MB_ETH_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_lmb_bram_0 || ORIG_REF_NAME==MB_ETH_lmb_bram_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_microblaze_0_axi_periph_0/MB_ETH_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MB_ETH_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_microblaze_0_axi_intc_0/MB_ETH_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_microblaze_0_axi_intc_0 || ORIG_REF_NAME==MB_ETH_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_microblaze_0_xlconcat_0/MB_ETH_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_microblaze_0_xlconcat_0 || ORIG_REF_NAME==MB_ETH_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_mdm_1_0/MB_ETH_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_mdm_1_0 || ORIG_REF_NAME==MB_ETH_mdm_1_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_clk_wiz_1_0/MB_ETH_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_clk_wiz_1_0 || ORIG_REF_NAME==MB_ETH_clk_wiz_1_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_rst_clk_wiz_1_100M_0/MB_ETH_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MB_ETH_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_xbar_0/MB_ETH_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_xbar_0 || ORIG_REF_NAME==MB_ETH_xbar_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_mig_7series_0_0/MB_ETH_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_mig_7series_0_0 || ORIG_REF_NAME==MB_ETH_mig_7series_0_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_mii_to_rmii_0_0/MB_ETH_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_mii_to_rmii_0_0 || ORIG_REF_NAME==MB_ETH_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_axi_uartlite_0_0/MB_ETH_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_axi_uartlite_0_0 || ORIG_REF_NAME==MB_ETH_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_axi_ethernetlite_0_0/MB_ETH_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_axi_ethernetlite_0_0 || ORIG_REF_NAME==MB_ETH_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_axi_timer_0_0/MB_ETH_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_axi_timer_0_0 || ORIG_REF_NAME==MB_ETH_axi_timer_0_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_axi_smc_0/MB_ETH_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_axi_smc_0 || ORIG_REF_NAME==MB_ETH_axi_smc_0} -quiet] -quiet

# IP: bd/MB_ETH/ip/MB_ETH_rst_mig_7series_0_81M_0/MB_ETH_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_ETH_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==MB_ETH_rst_mig_7series_0_81M_0} -quiet] -quiet

# XDC: bd/MB_ETH/MB_ETH_ooc.xdc
